project:
  type: website
  output-dir: docs

website:
  title: "Gary A. Wagner"
  site-url: ""
  description: "Gary A. Wagner website"
  open-graph:
    locale: en_US
  navbar:
    search: false
    right:
      - text: "Home"
        href: index.html
      - text: "CV and Recent Papers"
        href: papers
      - text: "LEAF Reports"
        href: leaf
  page-footer:
    left: ""
search: false
format:
  html:
    theme: [flatly]
    css: styles.css